"""add summary to attachments

Revision ID: 5a4949da88a1
Revises: 89814099dc3e
Create Date: 2026-01-07 18:41:06.851926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4949da88a1'
down_revision = '89814099dc3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'summary')
    # ### end Alembic commands ###
