"""add raw_email_data for retry support

Revision ID: 89814099dc3e
Revises: 002
Create Date: 2026-01-06 20:17:16.994739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89814099dc3e'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('raw_email_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'raw_email_data')
    # ### end Alembic commands ###
